# System user
system_user: vagrant

workspace: multi-study

# Databases
databases:
  postgresql:
    type: postgresql
    user: postgres
    password: postgres
    host: localhost
    port: 5432
    name: multi_study

# Dirs
home_dir: /home/vagrant
root_dir: /vagrant

# Managed domains
domains:
  - multi-study.com

# Python
virtualenv: multi-study
python_executable: python3
python_version: 3

# Node
nvm_version: v0.20.0
node_version: v0.10.34
node_packages:
  - bower
  - gulp

# Vagrant
vagrant_box: ubuntu/trusty64
vagrant_hostname: vagrant.multi-study.local
vagrant_ip: 10.1.1.3
vagrant_memory: 4092
vagrant_cpus: 4
