---

- name: install postgresql packages
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - libpq-dev
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: ensure postgresql is running
  service: name=postgresql state=started

- name: create postgresql database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ item.value.name }} encoding='UTF-8' state=present
  with_dict: databases
  when: item.value.type and item.value.type == "postgresql"

- name: create postgresql user
  sudo: yes
  sudo_user: postgres
  postgresql_user: db={{ item.value.name }} name={{ item.value.user }} password={{ item.value.password }} state=present
  with_dict: databases
  when: item.value.type == "postgresql"

- name: grant database privileges
  sudo: yes
  sudo_user: postgres
  postgresql_privs: db={{ item.value.name }} privs=ALL type=database obj={{ item.value.name }} role={{ item.value.user }}
  with_dict: databases
  when: item.value.type == "postgresql"
