---

- name: install uwsgi
  sudo: yes
  apt: pkg=uwsgi state=present

- name: install python2 uwsgi support
  sudo: yes
  apt: pkg=uwsgi-plugin-python state=present
  when: not python_version or python_version == 2

- name: install python3 uwsgi support
  sudo: yes
  apt: pkg=uwsgi-plugin-python3 state=present
  when: python_version and python_version == 3

- name: copy uwsgi apps
  template: src="{{ item | basename }}" dest="/etc/uwsgi/apps-available/{{ workspace }}-{{ item | basename | replace('.j2', '') }}"
  sudo: yes
  with_fileglob:
    - "{{ root_dir }}/ansible/roles/uwsgi/templates/*"
  notify:
    - restart uwsgi

- name: enable uwsgi apps
  file: src="/etc/uwsgi/apps-available/{{ workspace }}-{{ item | basename | replace('.j2', '') }}" dest="/etc/uwsgi/apps-enabled/{{ workspace }}-{{ item | basename | replace('.j2', '') }}" state=link
  sudo: yes
  with_fileglob:
    - "{{ root_dir }}/ansible/roles/uwsgi/templates/*"
  notify:
    - restart uwsgi
